#include "PinyinHelper.hpp"

const std::unordered_map<std::string, std::wstring> XiaoHePinyinArr = {
	{"a", L"aa"}, {"ai", L"ai"}, {"an", L"an"}, {"ang", L"ah"}, {"ao", L"ao"}, {"ba", L"ba"}, {"bai", L"bd"}, {"ban", L"bj"},
	{"bang", L"bh"}, {"bao", L"bc"}, {"bei", L"bw"}, {"ben", L"bf"}, {"beng", L"bg"}, {"bi", L"bi"}, {"bian", L"bm"}, {"biao", L"bn"},
	{"bie", L"bp"}, {"bin", L"bb"}, {"bing", L"bk"}, {"bo", L"bo"}, {"bu", L"bu"}, {"ca", L"ca"}, {"cai", L"cd"}, {"can", L"cj"},
	{"cang", L"ch"}, {"cao", L"cc"}, {"ce", L"ce"}, {"ceng", L"cg"}, {"cha", L"ia"}, {"chai", L"id"}, {"chan", L"ij"}, {"chang", L"ih"},
	{"chao", L"ic"}, {"che", L"ie"}, {"chen", L"if"}, {"cheng", L"ig"}, {"chi", L"ii"}, {"chong", L"is"}, {"chou", L"iz"}, {"chu", L"iu"},
	{"chuai", L"ik"}, {"chuan", L"ir"}, {"chuang", L"il"}, {"chui", L"iv"}, {"chun", L"iy"}, {"chuo", L"io"}, {"ci", L"ci"},
	{"cong", L"cs"}, {"cou", L"cz"}, {"cu", L"cu"}, {"cuan", L"cr"}, {"cui", L"cv"}, {"cun", L"cy"}, {"cuo", L"co"}, {"da", L"da"},
	{"dai", L"dd"}, {"dan", L"dj"}, {"dang", L"dh"}, {"dao", L"dc"}, {"de", L"de"}, {"deng", L"dg"}, {"di", L"di"}, {"dian", L"dm"},
	{"diao", L"dn"}, {"die", L"dp"}, {"ding", L"dk"}, {"diu", L"dq"}, {"dong", L"ds"}, {"dou", L"dz"}, {"du", L"du"}, {"duan", L"dr"},
	{"dui", L"dv"}, {"dun", L"dy"}, {"duo", L"do"}, {"e", L"ee"}, {"en", L"en"}, {"er", L"er"}, {"fa", L"fa"}, {"fan", L"fj"},
	{"fang", L"fh"}, {"fei", L"fw"}, {"fen", L"ff"}, {"feng", L"fg"}, {"fo", L"fo"}, {"fou", L"fz"}, {"fu", L"fu"}, {"ga", L"ga"},
	{"gai", L"gd"}, {"gan", L"gj"}, {"gang", L"gh"}, {"gao", L"gc"}, {"ge", L"ge"}, {"gei", L"gw"}, {"gen", L"gf"}, {"geng", L"gg"},
	{"gong", L"gs"}, {"gou", L"gz"}, {"gu", L"gu"}, {"gua", L"gx"}, {"guai", L"gk"}, {"guan", L"gr"}, {"guang", L"gl"}, {"gui", L"gv"},
	{"gun", L"gy"}, {"guo", L"go"}, {"ha", L"ha"}, {"hai", L"hd"}, {"han", L"hj"}, {"hang", L"hh"}, {"hao", L"hc"}, {"he", L"he"},
	{"hei", L"hw"}, {"hen", L"hf"}, {"heng", L"hg"}, {"hong", L"hs"}, {"hou", L"hz"}, {"hu", L"hu"}, {"hua", L"hx"}, {"huai", L"hk"},
	{"huan", L"hr"}, {"huang", L"hl"}, {"hui", L"hv"}, {"hun", L"hy"}, {"huo", L"ho"}, {"ji", L"ji"}, {"jia", L"jx"}, {"jian", L"jm"},
	{"jiang", L"jl"}, {"jiao", L"jn"}, {"jie", L"jp"}, {"jin", L"jb"}, {"jing", L"jk"}, {"jiong", L"js"}, {"jiu", L"jq"}, {"ju", L"ju"},
	{"juan", L"jr"}, {"jue", L"jt"}, {"jun", L"jy"}, {"ka", L"ka"}, {"kai", L"kd"}, {"kan", L"kj"}, {"kang", L"kh"}, {"kao", L"kc"},
	{"ke", L"ke"}, {"ken", L"kf"}, {"keng", L"kg"}, {"kong", L"ks"}, {"kou", L"kz"}, {"ku", L"ku"}, {"kua", L"kx"}, {"kuai", L"kk"},
	{"kuan", L"kr"}, {"kuang", L"kl"}, {"kui", L"kv"}, {"kun", L"ky"}, {"kuo", L"ko"}, {"la", L"la"}, {"lai", L"ld"}, {"lan", L"lj"},
	{"lang", L"lh"}, {"lao", L"lc"}, {"le", L"le"}, {"lei", L"lw"}, {"leng", L"lg"}, {"li", L"li"}, {"lia", L"lx"}, {"lian", L"lm"},
	{"liang", L"ll"}, {"liao", L"ln"}, {"lie", L"lp"}, {"lin", L"lb"}, {"ling", L"lk"}, {"liu", L"lq"}, {"long", L"ls"}, {"lou", L"lz"},
	{"lu", L"lu"}, {"lv", L"lv"}, {"luan", L"lr"}, {"lue", L"lt"}, {"lun", L"ly"}, {"luo", L"lo"}, {"ma", L"ma"}, {"mai", L"md"},
	{"man", L"mj"}, {"mang", L"mh"}, {"mao", L"mc"}, {"me", L"me"}, {"mei", L"mw"}, {"men", L"mf"}, {"meng", L"mg"}, {"mi", L"mi"},
	{"mian", L"mm"}, {"miao", L"mn"}, {"mie", L"mp"}, {"min", L"mb"}, {"ming", L"mk"}, {"miu", L"mq"}, {"mo", L"mo"}, {"mou", L"mz"},
	{"mu", L"mu"}, {"na", L"na"}, {"nai", L"nd"}, {"nan", L"nj"}, {"nang", L"nh"}, {"nao", L"nc"}, {"ne", L"ne"}, {"nei", L"nw"},
	{"nen", L"nf"}, {"neng", L"ng"}, {"ni", L"ni"}, {"nian", L"nm"}, {"niang", L"nl"}, {"niao", L"nn"}, {"nie", L"np"}, {"nin", L"nb"},
	{"ning", L"nk"}, {"niu", L"nq"}, {"nong", L"ns"}, {"nu", L"nu"}, {"nv", L"nv"}, {"nuan", L"nr"}, {"nue", L"nt"}, {"nuo", L"no"},
	{"o", L"oo"}, {"ou", L"ou"}, {"pa", L"pa"}, {"pai", L"pd"}, {"pan", L"pj"}, {"pang", L"ph"}, {"pao", L"pc"}, {"pei", L"pw"},
	{"pen", L"pf"}, {"peng", L"pg"}, {"pi", L"pi"}, {"pian", L"pm"}, {"piao", L"pn"}, {"pie", L"pp"}, {"pin", L"pb"}, {"ping", L"pk"},
	{"po", L"po"}, {"pu", L"pu"}, {"qi", L"qi"}, {"qia", L"qx"}, {"qian", L"qm"}, {"qiang", L"ql"}, {"qiao", L"qn"}, {"qie", L"qp"},
	{"qin", L"qb"}, {"qing", L"qk"}, {"qiong", L"qs"}, {"qiu", L"qq"}, {"qu", L"qu"}, {"quan", L"qr"}, {"que", L"qt"}, {"qun", L"qy"},
	{"ran", L"rj"}, {"rang", L"rh"}, {"rao", L"rc"}, {"re", L"re"}, {"ren", L"rf"}, {"reng", L"rg"}, {"ri", L"ri"}, {"rong", L"rs"},
	{"rou", L"rz"}, {"ru", L"ru"}, {"ruan", L"rr"}, {"rui", L"rv"}, {"run", L"ry"}, {"ruo", L"ro"}, {"sa", L"sa"}, {"sai", L"sd"},
	{"san", L"sj"}, {"sang", L"sh"}, {"sao", L"sc"}, {"se", L"se"}, {"sen", L"sf"}, {"seng", L"sg"}, {"sha", L"ua"}, {"shai", L"ud"},
	{"shan", L"uj"}, {"shang", L"uh"}, {"shao", L"uc"}, {"she", L"ue"}, {"shen", L"uf"}, {"sheng", L"ug"}, {"shi", L"ui"}, {"shou", L"uz"},
	{"shu", L"uu"}, {"shua", L"ux"}, {"shuai", L"uk"}, {"shuan", L"ur"}, {"shuang", L"ul"}, {"shui", L"uv"}, {"shun", L"uy"},
	{"shuo", L"uo"}, {"si", L"si"}, {"song", L"ss"}, {"sou", L"sz"}, {"su", L"su"}, {"suan", L"sr"}, {"sui", L"sv"}, {"sun", L"sy"},
	{"suo", L"so"}, {"ta", L"ta"}, {"tai", L"td"}, {"tan", L"tj"}, {"tang", L"th"}, {"tao", L"tc"}, {"te", L"te"}, {"teng", L"tg"},
	{"ti", L"ti"}, {"tian", L"tm"}, {"tiao", L"tn"}, {"tie", L"tp"}, {"ting", L"tk"}, {"tong", L"ts"}, {"tou", L"tz"}, {"tu", L"tu"},
	{"tuan", L"tr"}, {"tui", L"tv"}, {"tun", L"ty"}, {"tuo", L"to"}, {"wa", L"wa"}, {"wai", L"wd"}, {"wan", L"wj"}, {"wang", L"wh"},
	{"wei", L"ww"}, {"wen", L"wf"}, {"weng", L"wg"}, {"wo", L"wo"}, {"wu", L"wu"}, {"xi", L"xi"}, {"xia", L"xx"}, {"xian", L"xm"},
	{"xiang", L"xl"}, {"xiao", L"xn"}, {"xie", L"xp"}, {"xin", L"xb"}, {"xing", L"xk"}, {"xiong", L"xs"}, {"xiu", L"xq"}, {"xu", L"xu"},
	{"xuan", L"xr"}, {"xue", L"xt"}, {"xun", L"xy"}, {"ya", L"ya"}, {"yan", L"yj"}, {"yang", L"yh"}, {"yao", L"yc"}, {"ye", L"ye"},
	{"yi", L"yi"}, {"yin", L"yb"}, {"ying", L"yk"}, {"yo", L"yo"}, {"yong", L"ys"}, {"you", L"yz"}, {"yu", L"yu"}, {"yuan", L"yr"},
	{"yue", L"yt"}, {"yun", L"yy"}, {"za", L"za"}, {"zai", L"zd"}, {"zan", L"zj"}, {"zang", L"zh"}, {"zao", L"zc"}, {"ze", L"ze"},
	{"zei", L"zw"}, {"zen", L"zf"}, {"zeng", L"zg"}, {"zha", L"va"}, {"zhai", L"vd"}, {"zhan", L"vj"}, {"zhang", L"vh"}, {"zhao", L"vc"},
	{"zhe", L"ve"}, {"zhen", L"vf"}, {"zheng", L"vg"}, {"zhi", L"vi"}, {"zhong", L"vs"}, {"zhou", L"vz"}, {"zhu", L"vu"}, {"zhua", L"vx"},
	{"zhuai", L"vk"}, {"zhuan", L"vr"}, {"zhuang", L"vl"}, {"zhui", L"vv"}, {"zhun", L"vy"}, {"zhuo", L"vo"}, {"zi", L"zi"},
	{"zong", L"zs"}, {"zou", L"zz"}, {"zu", L"zu"}, {"zuan", L"zr"}, {"zui", L"zv"}, {"zun", L"zy"}, {"zuo", L"zo"}, {"ei", L"ei"},
	{"cen", L"cf"}, {"dei", L"dw"}, {"n", L"nn"}, {"lve", L"lt"}, {"nve", L"nt"}, {"pou", L"pz"}, {"zhei", L"vw"}, {"dia", L"dx"},
	{"nou", L"nz"},
};

const std::unordered_map<std::string, std::wstring> GuoBiaoPyArr = {
	{"a", L"aa"}, {"ai", L"ak"}, {"an", L"af"}, {"ang", L"ag"}, {"ao", L"ac"}, {"ba", L"ba"}, {"bai", L"bk"}, {"ban", L"bf"},
	{"bang", L"bg"}, {"bao", L"bc"}, {"bei", L"bb"}, {"ben", L"br"}, {"beng", L"bh"}, {"bi", L"bi"}, {"bian", L"bd"}, {"biao", L"bm"},
	{"bie", L"bt"}, {"bin", L"bl"}, {"bing", L"bj"}, {"bo", L"bo"}, {"bu", L"bu"}, {"ca", L"ca"}, {"cai", L"ck"}, {"can", L"cf"},
	{"cang", L"cg"}, {"cao", L"cc"}, {"ce", L"ce"}, {"ceng", L"ch"}, {"cha", L"ia"}, {"chai", L"ik"}, {"chan", L"if"}, {"chang", L"ig"},
	{"chao", L"ic"}, {"che", L"ie"}, {"chen", L"ir"}, {"cheng", L"ih"}, {"chi", L"ii"}, {"chong", L"is"}, {"chou", L"ip"}, {"chu", L"iu"},
	{"chuai", L"iy"}, {"chuan", L"iw"}, {"chuang", L"in"}, {"chui", L"iv"}, {"chun", L"iz"}, {"chuo", L"io"}, {"ci", L"ci"},
	{"cong", L"cs"}, {"cou", L"cp"}, {"cu", L"cu"}, {"cuan", L"cw"}, {"cui", L"cv"}, {"cun", L"cz"}, {"cuo", L"co"}, {"da", L"da"},
	{"dai", L"dk"}, {"dan", L"df"}, {"dang", L"dg"}, {"dao", L"dc"}, {"de", L"de"}, {"deng", L"dh"}, {"di", L"di"}, {"dian", L"dd"},
	{"diao", L"dm"}, {"die", L"dt"}, {"ding", L"dj"}, {"diu", L"dy"}, {"dong", L"ds"}, {"dou", L"dp"}, {"du", L"du"}, {"duan", L"dw"},
	{"dui", L"dv"}, {"dun", L"dz"}, {"duo", L"do"}, {"e", L"ae"}, {"en", L"ar"}, {"er", L"al"}, {"fa", L"fa"}, {"fan", L"ff"},
	{"fang", L"fg"}, {"fei", L"fb"}, {"fen", L"fr"}, {"feng", L"fh"}, {"fo", L"fo"}, {"fou", L"fp"}, {"fu", L"fu"}, {"ga", L"ga"},
	{"gai", L"gk"}, {"gan", L"gf"}, {"gang", L"gg"}, {"gao", L"gc"}, {"ge", L"ge"}, {"gei", L"gb"}, {"gen", L"gr"}, {"geng", L"gh"},
	{"gong", L"gs"}, {"gou", L"gp"}, {"gu", L"gu"}, {"gua", L"gq"}, {"guai", L"gy"}, {"guan", L"gw"}, {"guang", L"gn"}, {"gui", L"gv"},
	{"gun", L"gz"}, {"guo", L"go"}, {"ha", L"ha"}, {"hai", L"hk"}, {"han", L"hf"}, {"hang", L"hg"}, {"hao", L"hc"}, {"he", L"he"},
	{"hei", L"hb"}, {"hen", L"hr"}, {"heng", L"hh"}, {"hong", L"hs"}, {"hou", L"hp"}, {"hu", L"hu"}, {"hua", L"hq"}, {"huai", L"hy"},
	{"huan", L"hw"}, {"huang", L"hn"}, {"hui", L"hv"}, {"hun", L"hz"}, {"huo", L"ho"}, {"ji", L"ji"}, {"jia", L"jq"}, {"jian", L"jd"},
	{"jiang", L"jn"}, {"jiao", L"jm"}, {"jie", L"jt"}, {"jin", L"jl"}, {"jing", L"jj"}, {"jiong", L"js"}, {"jiu", L"jy"}, {"ju", L"ju"},
	{"juan", L"jw"}, {"jue", L"jx"}, {"jun", L"jz"}, {"ka", L"ka"}, {"kai", L"kk"}, {"kan", L"kf"}, {"kang", L"kg"}, {"kao", L"kc"},
	{"ke", L"ke"}, {"ken", L"kr"}, {"keng", L"kh"}, {"kong", L"ks"}, {"kou", L"kp"}, {"ku", L"ku"}, {"kua", L"kq"}, {"kuai", L"ky"},
	{"kuan", L"kw"}, {"kuang", L"kn"}, {"kui", L"kv"}, {"kun", L"kz"}, {"kuo", L"ko"}, {"la", L"la"}, {"lai", L"lk"}, {"lan", L"lf"},
	{"lang", L"lg"}, {"lao", L"lc"}, {"le", L"le"}, {"lei", L"lb"}, {"leng", L"lh"}, {"li", L"li"}, {"lia", L"lq"}, {"lian", L"ld"},
	{"liang", L"ln"}, {"liao", L"lm"}, {"lie", L"lt"}, {"lin", L"ll"}, {"ling", L"lj"}, {"liu", L"ly"}, {"long", L"ls"}, {"lou", L"lp"},
	{"lu", L"lu"}, {"lv", L"lv"}, {"luan", L"lw"}, {"lue", L"lx"}, {"lun", L"lz"}, {"luo", L"lo"}, {"ma", L"ma"}, {"mai", L"mk"},
	{"man", L"mf"}, {"mang", L"mg"}, {"mao", L"mc"}, {"me", L"me"}, {"mei", L"mb"}, {"men", L"mr"}, {"meng", L"mh"}, {"mi", L"mi"},
	{"mian", L"md"}, {"miao", L"mm"}, {"mie", L"mt"}, {"min", L"ml"}, {"ming", L"mj"}, {"miu", L"my"}, {"mo", L"mo"}, {"mou", L"mp"},
	{"mu", L"mu"}, {"na", L"na"}, {"nai", L"nk"}, {"nan", L"nf"}, {"nang", L"ng"}, {"nao", L"nc"}, {"ne", L"ne"}, {"nei", L"nb"},
	{"nen", L"nr"}, {"neng", L"nh"}, {"ni", L"ni"}, {"nian", L"nd"}, {"niang", L"nn"}, {"niao", L"nm"}, {"nie", L"nt"}, {"nin", L"nl"},
	{"ning", L"nj"}, {"niu", L"ny"}, {"nong", L"ns"}, {"nu", L"nu"}, {"nv", L"nv"}, {"nuan", L"nw"}, {"nue", L"nx"}, {"nuo", L"no"},
	{"o", L"ao"}, {"ou", L"ap"}, {"pa", L"pa"}, {"pai", L"pk"}, {"pan", L"pf"}, {"pang", L"pg"}, {"pao", L"pc"}, {"pei", L"pb"},
	{"pen", L"pr"}, {"peng", L"ph"}, {"pi", L"pi"}, {"pian", L"pd"}, {"piao", L"pm"}, {"pie", L"pt"}, {"pin", L"pl"}, {"ping", L"pj"},
	{"po", L"po"}, {"pu", L"pu"}, {"qi", L"qi"}, {"qia", L"qq"}, {"qian", L"qd"}, {"qiang", L"qn"}, {"qiao", L"qm"}, {"qie", L"qt"},
	{"qin", L"ql"}, {"qing", L"qj"}, {"qiong", L"qs"}, {"qiu", L"qy"}, {"qu", L"qu"}, {"quan", L"qw"}, {"que", L"qx"}, {"qun", L"qz"},
	{"ran", L"rf"}, {"rang", L"rg"}, {"rao", L"rc"}, {"re", L"re"}, {"ren", L"rr"}, {"reng", L"rh"}, {"ri", L"ri"}, {"rong", L"rs"},
	{"rou", L"rp"}, {"ru", L"ru"}, {"ruan", L"rw"}, {"rui", L"rv"}, {"run", L"rz"}, {"ruo", L"ro"}, {"sa", L"sa"}, {"sai", L"sk"},
	{"san", L"sf"}, {"sang", L"sg"}, {"sao", L"sc"}, {"se", L"se"}, {"sen", L"sr"}, {"seng", L"sh"}, {"sha", L"ua"}, {"shai", L"uk"},
	{"shan", L"uf"}, {"shang", L"ug"}, {"shao", L"uc"}, {"she", L"ue"}, {"shen", L"ur"}, {"sheng", L"uh"}, {"shi", L"ui"}, {"shou", L"up"},
	{"shu", L"uu"}, {"shua", L"uq"}, {"shuai", L"uy"}, {"shuan", L"uw"}, {"shuang", L"un"}, {"shui", L"uv"}, {"shun", L"uz"},
	{"shuo", L"uo"}, {"si", L"si"}, {"song", L"ss"}, {"sou", L"sp"}, {"su", L"su"}, {"suan", L"sw"}, {"sui", L"sv"}, {"sun", L"sz"},
	{"suo", L"so"}, {"ta", L"ta"}, {"tai", L"tk"}, {"tan", L"tf"}, {"tang", L"tg"}, {"tao", L"tc"}, {"te", L"te"}, {"teng", L"th"},
	{"ti", L"ti"}, {"tian", L"td"}, {"tiao", L"tm"}, {"tie", L"tt"}, {"ting", L"tj"}, {"tong", L"ts"}, {"tou", L"tp"}, {"tu", L"tu"},
	{"tuan", L"tw"}, {"tui", L"tv"}, {"tun", L"tz"}, {"tuo", L"to"}, {"wa", L"wa"}, {"wai", L"wk"}, {"wan", L"wf"}, {"wang", L"wg"},
	{"wei", L"wb"}, {"wen", L"wr"}, {"weng", L"wh"}, {"wo", L"wo"}, {"wu", L"wu"}, {"xi", L"xi"}, {"xia", L"xq"}, {"xian", L"xd"},
	{"xiang", L"xn"}, {"xiao", L"xm"}, {"xie", L"xt"}, {"xin", L"xl"}, {"xing", L"xj"}, {"xiong", L"xs"}, {"xiu", L"xy"}, {"xu", L"xu"},
	{"xuan", L"xw"}, {"xue", L"xx"}, {"xun", L"xz"}, {"ya", L"ya"}, {"yan", L"yf"}, {"yang", L"yg"}, {"yao", L"yc"}, {"ye", L"ye"},
	{"yi", L"yi"}, {"yin", L"yl"}, {"ying", L"yj"}, {"yo", L"yo"}, {"yong", L"ys"}, {"you", L"yp"}, {"yu", L"yu"}, {"yuan", L"yw"},
	{"yue", L"yx"}, {"yun", L"yz"}, {"za", L"za"}, {"zai", L"zk"}, {"zan", L"zf"}, {"zang", L"zg"}, {"zao", L"zc"}, {"ze", L"ze"},
	{"zei", L"zb"}, {"zen", L"zr"}, {"zeng", L"zh"}, {"zha", L"va"}, {"zhai", L"vk"}, {"zhan", L"vf"}, {"zhang", L"vg"}, {"zhao", L"vc"},
	{"zhe", L"ve"}, {"zhen", L"vr"}, {"zheng", L"vh"}, {"zhi", L"vi"}, {"zhong", L"vs"}, {"zhou", L"vp"}, {"zhu", L"vu"}, {"zhua", L"vq"},
	{"zhuai", L"vy"}, {"zhuan", L"vw"}, {"zhuang", L"vn"}, {"zhui", L"vv"}, {"zhun", L"vz"}, {"zhuo", L"vo"}, {"zi", L"zi"},
	{"zong", L"zs"}, {"zou", L"zp"}, {"zu", L"zu"}, {"zuan", L"zw"}, {"zui", L"zv"}, {"zun", L"zz"}, {"zuo", L"zo"}, {"ei", L"ab"},
	{"cen", L"cr"}, {"dei", L"db"}, {"n", L"n"}, {"lve", L"lx"}, {"nve", L"nx"}, {"pou", L"pp"}, {"zhei", L"vb"}, {"dia", L"dq"},
	{"nou", L"np"},
};
const std::unordered_map<std::string, std::wstring> ZiGuangPyArr = {
	{"a", L"oa"}, {"ai", L"op"}, {"an", L"or"}, {"ang", L"os"}, {"ao", L"oq"}, {"ba", L"ba"}, {"bai", L"bp"}, {"ban", L"br"},
	{"bang", L"bs"}, {"bao", L"bq"}, {"bei", L"bk"}, {"ben", L"bw"}, {"beng", L"bt"}, {"bi", L"bi"}, {"bian", L"bf"}, {"biao", L"bb"},
	{"bie", L"bd"}, {"bin", L"by"}, {"bing", L"bz"}, {"bo", L"bo"}, {"bu", L"bu"}, {"ca", L"ca"}, {"cai", L"cp"}, {"can", L"cr"},
	{"cang", L"cs"}, {"cao", L"cq"}, {"ce", L"ce"}, {"ceng", L"ct"}, {"cha", L"aa"}, {"chai", L"ap"}, {"chan", L"ar"}, {"chang", L"as"},
	{"chao", L"aq"}, {"che", L"ae"}, {"chen", L"aw"}, {"cheng", L"at"}, {"chi", L"ai"}, {"chong", L"ah"}, {"chou", L"az"}, {"chu", L"au"},
	{"chuai", L"ay"}, {"chuan", L"al"}, {"chuang", L"ag"}, {"chui", L"an"}, {"chun", L"am"}, {"chuo", L"ao"}, {"ci", L"ci"},
	{"cong", L"ch"}, {"cou", L"cz"}, {"cu", L"cu"}, {"cuan", L"cl"}, {"cui", L"cn"}, {"cun", L"cm"}, {"cuo", L"co"}, {"da", L"da"},
	{"dai", L"dp"}, {"dan", L"dr"}, {"dang", L"ds"}, {"dao", L"dq"}, {"de", L"de"}, {"deng", L"dt"}, {"di", L"di"}, {"dian", L"df"},
	{"diao", L"db"}, {"die", L"dd"}, {"ding", L"dz"}, {"diu", L"dj"}, {"dong", L"dh"}, {"dou", L"dz"}, {"du", L"du"}, {"duan", L"dl"},
	{"dui", L"dn"}, {"dun", L"dm"}, {"duo", L"do"}, {"e", L"oe"}, {"en", L"ow"}, {"er", L"oj"}, {"fa", L"fa"}, {"fan", L"fr"},
	{"fang", L"fs"}, {"fei", L"fk"}, {"fen", L"fw"}, {"feng", L"ft"}, {"fo", L"fo"}, {"fou", L"fz"}, {"fu", L"fu"}, {"ga", L"ga"},
	{"gai", L"gp"}, {"gan", L"gr"}, {"gang", L"gs"}, {"gao", L"gq"}, {"ge", L"ge"}, {"gei", L"gk"}, {"gen", L"gw"}, {"geng", L"gt"},
	{"gong", L"gh"}, {"gou", L"gz"}, {"gu", L"gu"}, {"gua", L"gx"}, {"guai", L"gy"}, {"guan", L"gl"}, {"guang", L"gg"}, {"gui", L"gn"},
	{"gun", L"gm"}, {"guo", L"go"}, {"ha", L"ha"}, {"hai", L"hp"}, {"han", L"hr"}, {"hang", L"hs"}, {"hao", L"hq"}, {"he", L"he"},
	{"hei", L"hk"}, {"hen", L"hw"}, {"heng", L"ht"}, {"hong", L"hh"}, {"hou", L"hz"}, {"hu", L"hu"}, {"hua", L"hx"}, {"huai", L"hy"},
	{"huan", L"hl"}, {"huang", L"hg"}, {"hui", L"hn"}, {"hun", L"hm"}, {"huo", L"ho"}, {"ji", L"ji"}, {"jia", L"jx"}, {"jian", L"jf"},
	{"jiang", L"jg"}, {"jiao", L"jb"}, {"jie", L"jd"}, {"jin", L"jy"}, {"jing", L"jz"}, {"jiong", L"jh"}, {"jiu", L"jj"}, {"ju", L"ju"},
	{"juan", L"jl"}, {"jue", L"jn"}, {"jun", L"jm"}, {"ka", L"ka"}, {"kai", L"kp"}, {"kan", L"kr"}, {"kang", L"ks"}, {"kao", L"kq"},
	{"ke", L"ke"}, {"ken", L"kw"}, {"keng", L"kt"}, {"kong", L"kh"}, {"kou", L"kz"}, {"ku", L"ku"}, {"kua", L"kx"}, {"kuai", L"ky"},
	{"kuan", L"kl"}, {"kuang", L"kg"}, {"kui", L"kn"}, {"kun", L"km"}, {"kuo", L"ko"}, {"la", L"la"}, {"lai", L"lp"}, {"lan", L"lr"},
	{"lang", L"ls"}, {"lao", L"lq"}, {"le", L"le"}, {"lei", L"lk"}, {"leng", L"lt"}, {"li", L"li"}, {"lia", L"lx"}, {"lian", L"lf"},
	{"liang", L"lg"}, {"liao", L"lb"}, {"lie", L"ld"}, {"lin", L"ly"}, {"ling", L"lz"}, {"liu", L"lj"}, {"long", L"lh"}, {"lou", L"lz"},
	{"lu", L"lu"}, {"lv", L"lv"}, {"luan", L"ll"}, {"lue", L"ln"}, {"lun", L"lm"}, {"luo", L"lo"}, {"ma", L"ma"}, {"mai", L"mp"},
	{"man", L"mr"}, {"mang", L"ms"}, {"mao", L"mq"}, {"me", L"me"}, {"mei", L"mk"}, {"men", L"mw"}, {"meng", L"mt"}, {"mi", L"mi"},
	{"mian", L"mf"}, {"miao", L"mb"}, {"mie", L"md"}, {"min", L"my"}, {"ming", L"mz"}, {"miu", L"mj"}, {"mo", L"mo"}, {"mou", L"mz"},
	{"mu", L"mu"}, {"na", L"na"}, {"nai", L"np"}, {"nan", L"nr"}, {"nang", L"ns"}, {"nao", L"nq"}, {"ne", L"ne"}, {"nei", L"nk"},
	{"nen", L"nw"}, {"neng", L"nt"}, {"ni", L"ni"}, {"nian", L"nf"}, {"niang", L"ng"}, {"niao", L"nb"}, {"nie", L"nd"}, {"nin", L"ny"},
	{"ning", L"nz"}, {"niu", L"nj"}, {"nong", L"nh"}, {"nu", L"nu"}, {"nv", L"nv"}, {"nuan", L"nl"}, {"nue", L"nn"}, {"nuo", L"no"},
	{"o", L"oo"}, {"ou", L"oz"}, {"pa", L"pa"}, {"pai", L"pp"}, {"pan", L"pr"}, {"pang", L"ps"}, {"pao", L"pq"}, {"pei", L"pk"},
	{"pen", L"pw"}, {"peng", L"pt"}, {"pi", L"pi"}, {"pian", L"pf"}, {"piao", L"pb"}, {"pie", L"pd"}, {"pin", L"py"}, {"ping", L"pz"},
	{"po", L"po"}, {"pu", L"pu"}, {"qi", L"qi"}, {"qia", L"qx"}, {"qian", L"qf"}, {"qiang", L"qg"}, {"qiao", L"qb"}, {"qie", L"qd"},
	{"qin", L"qy"}, {"qing", L"qz"}, {"qiong", L"qh"}, {"qiu", L"qj"}, {"qu", L"qu"}, {"quan", L"ql"}, {"que", L"qn"}, {"qun", L"qm"},
	{"ran", L"rr"}, {"rang", L"rs"}, {"rao", L"rq"}, {"re", L"re"}, {"ren", L"rw"}, {"reng", L"rt"}, {"ri", L"ri"}, {"rong", L"rh"},
	{"rou", L"rz"}, {"ru", L"ru"}, {"ruan", L"rl"}, {"rui", L"rn"}, {"run", L"rm"}, {"ruo", L"ro"}, {"sa", L"sa"}, {"sai", L"sp"},
	{"san", L"sr"}, {"sang", L"ss"}, {"sao", L"sq"}, {"se", L"se"}, {"sen", L"sw"}, {"seng", L"st"}, {"sha", L"ia"}, {"shai", L"ip"},
	{"shan", L"ir"}, {"shang", L"is"}, {"shao", L"iq"}, {"she", L"ie"}, {"shen", L"iw"}, {"sheng", L"it"}, {"shi", L"ii"}, {"shou", L"iz"},
	{"shu", L"iu"}, {"shua", L"ix"}, {"shuai", L"iy"}, {"shuan", L"il"}, {"shuang", L"ig"}, {"shui", L"in"}, {"shun", L"im"},
	{"shuo", L"io"}, {"si", L"si"}, {"song", L"sh"}, {"sou", L"sz"}, {"su", L"su"}, {"suan", L"sl"}, {"sui", L"sn"}, {"sun", L"sm"},
	{"suo", L"so"}, {"ta", L"ta"}, {"tai", L"tp"}, {"tan", L"tr"}, {"tang", L"ts"}, {"tao", L"tq"}, {"te", L"te"}, {"teng", L"tt"},
	{"ti", L"ti"}, {"tian", L"tf"}, {"tiao", L"tb"}, {"tie", L"td"}, {"ting", L"tz"}, {"tong", L"th"}, {"tou", L"tz"}, {"tu", L"tu"},
	{"tuan", L"tl"}, {"tui", L"tn"}, {"tun", L"tm"}, {"tuo", L"to"}, {"wa", L"wa"}, {"wai", L"wp"}, {"wan", L"wr"}, {"wang", L"ws"},
	{"wei", L"wk"}, {"wen", L"ww"}, {"weng", L"wt"}, {"wo", L"wo"}, {"wu", L"wu"}, {"xi", L"xi"}, {"xia", L"xx"}, {"xian", L"xf"},
	{"xiang", L"xg"}, {"xiao", L"xb"}, {"xie", L"xd"}, {"xin", L"xy"}, {"xing", L"xz"}, {"xiong", L"xh"}, {"xiu", L"xj"}, {"xu", L"xu"},
	{"xuan", L"xl"}, {"xue", L"xn"}, {"xun", L"xm"}, {"ya", L"ya"}, {"yan", L"yr"}, {"yang", L"ys"}, {"yao", L"yq"}, {"ye", L"ye"},
	{"yi", L"yi"}, {"yin", L"yy"}, {"ying", L"yz"}, {"yo", L"yo"}, {"yong", L"yh"}, {"you", L"yz"}, {"yu", L"yu"}, {"yuan", L"yl"},
	{"yue", L"yn"}, {"yun", L"ym"}, {"za", L"za"}, {"zai", L"zp"}, {"zan", L"zr"}, {"zang", L"zs"}, {"zao", L"zq"}, {"ze", L"ze"},
	{"zei", L"zk"}, {"zen", L"zw"}, {"zeng", L"zt"}, {"zha", L"ua"}, {"zhai", L"up"}, {"zhan", L"ur"}, {"zhang", L"us"}, {"zhao", L"uq"},
	{"zhe", L"ue"}, {"zhen", L"uw"}, {"zheng", L"ut"}, {"zhi", L"ui"}, {"zhong", L"uh"}, {"zhou", L"uz"}, {"zhu", L"uu"}, {"zhua", L"ux"},
	{"zhuai", L"uy"}, {"zhuan", L"ul"}, {"zhuang", L"ug"}, {"zhui", L"un"}, {"zhun", L"um"}, {"zhuo", L"uo"}, {"zi", L"zi"},
	{"zong", L"zh"}, {"zou", L"zz"}, {"zu", L"zu"}, {"zuan", L"zl"}, {"zui", L"zn"}, {"zun", L"zm"}, {"zuo", L"zo"}, {"ei", L"ok"},
	{"cen", L"cw"}, {"dei", L"dk"}, {"n", L"n"}, {"lve", L"ln"}, {"nve", L"nn"}, {"pou", L"pz"}, {"zhei", L"uk"}, {"dia", L"dx"},
	{"nou", L"nz"},
};

const std::unordered_map<std::string, std::wstring> PlusPlusPyArr = {
	{"a", L"aa"}, {"ai", L"as"}, {"an", L"af"}, {"ang", L"ag"}, {"ao", L"ad"}, {"ba", L"ba"}, {"bai", L"bs"}, {"ban", L"bf"},
	{"bang", L"bg"}, {"bao", L"bd"}, {"bei", L"bw"}, {"ben", L"br"}, {"beng", L"bt"}, {"bi", L"bi"}, {"bian", L"bj"}, {"biao", L"bk"},
	{"bie", L"bm"}, {"bin", L"bl"}, {"bing", L"bq"}, {"bo", L"bo"}, {"bu", L"bu"}, {"ca", L"ca"}, {"cai", L"cs"}, {"can", L"cf"},
	{"cang", L"cg"}, {"cao", L"cd"}, {"ce", L"ce"}, {"ceng", L"ct"}, {"cha", L"ua"}, {"chai", L"us"}, {"chan", L"uf"}, {"chang", L"ug"},
	{"chao", L"ud"}, {"che", L"ue"}, {"chen", L"ur"}, {"cheng", L"ut"}, {"chi", L"ui"}, {"chong", L"uy"}, {"chou", L"up"}, {"chu", L"uu"},
	{"chuai", L"ux"}, {"chuan", L"uc"}, {"chuang", L"uh"}, {"chui", L"uv"}, {"chun", L"uz"}, {"chuo", L"uo"}, {"ci", L"ci"},
	{"cong", L"cy"}, {"cou", L"cp"}, {"cu", L"cu"}, {"cuan", L"cc"}, {"cui", L"cv"}, {"cun", L"cz"}, {"cuo", L"co"}, {"da", L"da"},
	{"dai", L"ds"}, {"dan", L"df"}, {"dang", L"dg"}, {"dao", L"dd"}, {"de", L"de"}, {"deng", L"dt"}, {"di", L"di"}, {"dian", L"dj"},
	{"diao", L"dk"}, {"die", L"dm"}, {"ding", L"dq"}, {"diu", L"dn"}, {"dong", L"dy"}, {"dou", L"dp"}, {"du", L"du"}, {"duan", L"dc"},
	{"dui", L"dv"}, {"dun", L"dz"}, {"duo", L"do"}, {"e", L"ee"}, {"en", L"er"}, {"er", L"eq"}, {"fa", L"fa"}, {"fan", L"ff"},
	{"fang", L"fg"}, {"fei", L"fw"}, {"fen", L"fr"}, {"feng", L"ft"}, {"fo", L"fo"}, {"fou", L"fp"}, {"fu", L"fu"}, {"ga", L"ga"},
	{"gai", L"gs"}, {"gan", L"gf"}, {"gang", L"gg"}, {"gao", L"gd"}, {"ge", L"ge"}, {"gei", L"gw"}, {"gen", L"gr"}, {"geng", L"gt"},
	{"gong", L"gy"}, {"gou", L"gp"}, {"gu", L"gu"}, {"gua", L"gb"}, {"guai", L"gx"}, {"guan", L"gc"}, {"guang", L"gh"}, {"gui", L"gv"},
	{"gun", L"gz"}, {"guo", L"go"}, {"ha", L"ha"}, {"hai", L"hs"}, {"han", L"hf"}, {"hang", L"hg"}, {"hao", L"hd"}, {"he", L"he"},
	{"hei", L"hw"}, {"hen", L"hr"}, {"heng", L"ht"}, {"hong", L"hy"}, {"hou", L"hp"}, {"hu", L"hu"}, {"hua", L"hb"}, {"huai", L"hx"},
	{"huan", L"hc"}, {"huang", L"hh"}, {"hui", L"hv"}, {"hun", L"hz"}, {"huo", L"ho"}, {"ji", L"ji"}, {"jia", L"jb"}, {"jian", L"jj"},
	{"jiang", L"jh"}, {"jiao", L"jk"}, {"jie", L"jm"}, {"jin", L"jl"}, {"jing", L"jq"}, {"jiong", L"jy"}, {"jiu", L"jn"}, {"ju", L"ju"},
	{"juan", L"jc"}, {"jue", L"jx"}, {"jun", L"jz"}, {"ka", L"ka"}, {"kai", L"ks"}, {"kan", L"kf"}, {"kang", L"kg"}, {"kao", L"kd"},
	{"ke", L"ke"}, {"ken", L"kr"}, {"keng", L"kt"}, {"kong", L"ky"}, {"kou", L"kp"}, {"ku", L"ku"}, {"kua", L"kb"}, {"kuai", L"kx"},
	{"kuan", L"kc"}, {"kuang", L"kh"}, {"kui", L"kv"}, {"kun", L"kz"}, {"kuo", L"ko"}, {"la", L"la"}, {"lai", L"ls"}, {"lan", L"lf"},
	{"lang", L"lg"}, {"lao", L"ld"}, {"le", L"le"}, {"lei", L"lw"}, {"leng", L"lt"}, {"li", L"li"}, {"lia", L"lb"}, {"lian", L"lj"},
	{"liang", L"lh"}, {"liao", L"lk"}, {"lie", L"lm"}, {"lin", L"ll"}, {"ling", L"lq"}, {"liu", L"ln"}, {"long", L"ly"}, {"lou", L"lp"},
	{"lu", L"lu"}, {"lv", L"lv"}, {"luan", L"lc"}, {"lue", L"lx"}, {"lun", L"lz"}, {"luo", L"lo"}, {"ma", L"ma"}, {"mai", L"ms"},
	{"man", L"mf"}, {"mang", L"mg"}, {"mao", L"md"}, {"me", L"me"}, {"mei", L"mw"}, {"men", L"mr"}, {"meng", L"mt"}, {"mi", L"mi"},
	{"mian", L"mj"}, {"miao", L"mk"}, {"mie", L"mm"}, {"min", L"ml"}, {"ming", L"mq"}, {"miu", L"mn"}, {"mo", L"mo"}, {"mou", L"mp"},
	{"mu", L"mu"}, {"na", L"na"}, {"nai", L"ns"}, {"nan", L"nf"}, {"nang", L"ng"}, {"nao", L"nd"}, {"ne", L"ne"}, {"nei", L"nw"},
	{"nen", L"nr"}, {"neng", L"nt"}, {"ni", L"ni"}, {"nian", L"nj"}, {"niang", L"nh"}, {"niao", L"nk"}, {"nie", L"nm"}, {"nin", L"nl"},
	{"ning", L"nq"}, {"niu", L"nn"}, {"nong", L"ny"}, {"nu", L"nu"}, {"nv", L"nv"}, {"nuan", L"nc"}, {"nue", L"nx"}, {"nuo", L"no"},
	{"o", L"oo"}, {"ou", L"op"}, {"pa", L"pa"}, {"pai", L"ps"}, {"pan", L"pf"}, {"pang", L"pg"}, {"pao", L"pd"}, {"pei", L"pw"},
	{"pen", L"pr"}, {"peng", L"pt"}, {"pi", L"pi"}, {"pian", L"pj"}, {"piao", L"pk"}, {"pie", L"pm"}, {"pin", L"pl"}, {"ping", L"pq"},
	{"po", L"po"}, {"pu", L"pu"}, {"qi", L"qi"}, {"qia", L"qb"}, {"qian", L"qj"}, {"qiang", L"qh"}, {"qiao", L"qk"}, {"qie", L"qm"},
	{"qin", L"ql"}, {"qing", L"qq"}, {"qiong", L"qy"}, {"qiu", L"qn"}, {"qu", L"qu"}, {"quan", L"qc"}, {"que", L"qx"}, {"qun", L"qz"},
	{"ran", L"rf"}, {"rang", L"rg"}, {"rao", L"rd"}, {"re", L"re"}, {"ren", L"rr"}, {"reng", L"rt"}, {"ri", L"ri"}, {"rong", L"ry"},
	{"rou", L"rp"}, {"ru", L"ru"}, {"ruan", L"rc"}, {"rui", L"rv"}, {"run", L"rz"}, {"ruo", L"ro"}, {"sa", L"sa"}, {"sai", L"ss"},
	{"san", L"sf"}, {"sang", L"sg"}, {"sao", L"sd"}, {"se", L"se"}, {"sen", L"sr"}, {"seng", L"st"}, {"sha", L"ia"}, {"shai", L"is"},
	{"shan", L"if"}, {"shang", L"ig"}, {"shao", L"id"}, {"she", L"ie"}, {"shen", L"ir"}, {"sheng", L"it"}, {"shi", L"ii"}, {"shou", L"ip"},
	{"shu", L"iu"}, {"shua", L"ib"}, {"shuai", L"ix"}, {"shuan", L"ic"}, {"shuang", L"ih"}, {"shui", L"iv"}, {"shun", L"iz"},
	{"shuo", L"io"}, {"si", L"si"}, {"song", L"sy"}, {"sou", L"sp"}, {"su", L"su"}, {"suan", L"sc"}, {"sui", L"sv"}, {"sun", L"sz"},
	{"suo", L"so"}, {"ta", L"ta"}, {"tai", L"ts"}, {"tan", L"tf"}, {"tang", L"tg"}, {"tao", L"td"}, {"te", L"te"}, {"teng", L"tt"},
	{"ti", L"ti"}, {"tian", L"tj"}, {"tiao", L"tk"}, {"tie", L"tm"}, {"ting", L"tq"}, {"tong", L"ty"}, {"tou", L"tp"}, {"tu", L"tu"},
	{"tuan", L"tc"}, {"tui", L"tv"}, {"tun", L"tz"}, {"tuo", L"to"}, {"wa", L"wa"}, {"wai", L"ws"}, {"wan", L"wf"}, {"wang", L"wg"},
	{"wei", L"ww"}, {"wen", L"wr"}, {"weng", L"wt"}, {"wo", L"wo"}, {"wu", L"wu"}, {"xi", L"xi"}, {"xia", L"xb"}, {"xian", L"xj"},
	{"xiang", L"xh"}, {"xiao", L"xk"}, {"xie", L"xm"}, {"xin", L"xl"}, {"xing", L"xq"}, {"xiong", L"xy"}, {"xiu", L"xn"}, {"xu", L"xu"},
	{"xuan", L"xc"}, {"xue", L"xx"}, {"xun", L"xz"}, {"ya", L"ya"}, {"yan", L"yf"}, {"yang", L"yg"}, {"yao", L"yd"}, {"ye", L"ye"},
	{"yi", L"yi"}, {"yin", L"yl"}, {"ying", L"yq"}, {"yo", L"yo"}, {"yong", L"yy"}, {"you", L"yp"}, {"yu", L"yu"}, {"yuan", L"yc"},
	{"yue", L"yx"}, {"yun", L"yz"}, {"za", L"za"}, {"zai", L"zs"}, {"zan", L"zf"}, {"zang", L"zg"}, {"zao", L"zd"}, {"ze", L"ze"},
	{"zei", L"zw"}, {"zen", L"zr"}, {"zeng", L"zt"}, {"zha", L"va"}, {"zhai", L"vs"}, {"zhan", L"vf"}, {"zhang", L"vg"}, {"zhao", L"vd"},
	{"zhe", L"ve"}, {"zhen", L"vr"}, {"zheng", L"vt"}, {"zhi", L"vi"}, {"zhong", L"vy"}, {"zhou", L"vp"}, {"zhu", L"vu"}, {"zhua", L"vb"},
	{"zhuai", L"vx"}, {"zhuan", L"vc"}, {"zhuang", L"vh"}, {"zhui", L"vv"}, {"zhun", L"vz"}, {"zhuo", L"vo"}, {"zi", L"zi"},
	{"zong", L"zy"}, {"zou", L"zp"}, {"zu", L"zu"}, {"zuan", L"zc"}, {"zui", L"zv"}, {"zun", L"zz"}, {"zuo", L"zo"}, {"ei", L"ew"},
	{"cen", L"cr"}, {"dei", L"dw"}, {"n", L"n"}, {"lve", L"lx"}, {"nve", L"nx"}, {"pou", L"pp"}, {"zhei", L"vw"}, {"dia", L"db"},
	{"nou", L"np"},
};

const std::unordered_map<std::string, std::wstring> AbcPyArr = {
	{"a", L"oa"}, {"ai", L"ol"}, {"an", L"oj"}, {"ang", L"oh"}, {"ao", L"ok"}, {"ba", L"ba"}, {"bai", L"bl"}, {"ban", L"bj"},
	{"bang", L"bh"}, {"bao", L"bk"}, {"bei", L"bq"}, {"ben", L"bf"}, {"beng", L"bg"}, {"bi", L"bi"}, {"bian", L"bw"}, {"biao", L"bz"},
	{"bie", L"bx"}, {"bin", L"bc"}, {"bing", L"by"}, {"bo", L"bo"}, {"bu", L"bu"}, {"ca", L"ca"}, {"cai", L"cl"}, {"can", L"cj"},
	{"cang", L"ch"}, {"cao", L"ck"}, {"ce", L"ce"}, {"ceng", L"cg"}, {"cha", L"ea"}, {"chai", L"el"}, {"chan", L"ej"}, {"chang", L"eh"},
	{"chao", L"ek"}, {"che", L"ee"}, {"chen", L"ef"}, {"cheng", L"eg"}, {"chi", L"ei"}, {"chong", L"es"}, {"chou", L"eb"}, {"chu", L"eu"},
	{"chuai", L"ec"}, {"chuan", L"ep"}, {"chuang", L"et"}, {"chui", L"em"}, {"chun", L"en"}, {"chuo", L"eo"}, {"ci", L"ci"},
	{"cong", L"cs"}, {"cou", L"cb"}, {"cu", L"cu"}, {"cuan", L"cp"}, {"cui", L"cm"}, {"cun", L"cn"}, {"cuo", L"co"}, {"da", L"da"},
	{"dai", L"dl"}, {"dan", L"dj"}, {"dang", L"dh"}, {"dao", L"dk"}, {"de", L"de"}, {"deng", L"dg"}, {"di", L"di"}, {"dian", L"dw"},
	{"diao", L"dz"}, {"die", L"dx"}, {"ding", L"dy"}, {"diu", L"dr"}, {"dong", L"ds"}, {"dou", L"db"}, {"du", L"du"}, {"duan", L"dp"},
	{"dui", L"dm"}, {"dun", L"dn"}, {"duo", L"do"}, {"e", L"oe"}, {"en", L"of"}, {"er", L"or"}, {"fa", L"fa"}, {"fan", L"fj"},
	{"fang", L"fh"}, {"fei", L"fq"}, {"fen", L"ff"}, {"feng", L"fg"}, {"fo", L"fo"}, {"fou", L"fb"}, {"fu", L"fu"}, {"ga", L"ga"},
	{"gai", L"gl"}, {"gan", L"gj"}, {"gang", L"gh"}, {"gao", L"gk"}, {"ge", L"ge"}, {"gei", L"gq"}, {"gen", L"gf"}, {"geng", L"gg"},
	{"gong", L"gs"}, {"gou", L"gb"}, {"gu", L"gu"}, {"gua", L"gd"}, {"guai", L"gc"}, {"guan", L"gp"}, {"guang", L"gt"}, {"gui", L"gm"},
	{"gun", L"gn"}, {"guo", L"go"}, {"ha", L"ha"}, {"hai", L"hl"}, {"han", L"hj"}, {"hang", L"hh"}, {"hao", L"hk"}, {"he", L"he"},
	{"hei", L"hq"}, {"hen", L"hf"}, {"heng", L"hg"}, {"hong", L"hs"}, {"hou", L"hb"}, {"hu", L"hu"}, {"hua", L"hd"}, {"huai", L"hc"},
	{"huan", L"hp"}, {"huang", L"ht"}, {"hui", L"hm"}, {"hun", L"hn"}, {"huo", L"ho"}, {"ji", L"ji"}, {"jia", L"jd"}, {"jian", L"jw"},
	{"jiang", L"jt"}, {"jiao", L"jz"}, {"jie", L"jx"}, {"jin", L"jc"}, {"jing", L"jy"}, {"jiong", L"js"}, {"jiu", L"jr"}, {"ju", L"ju"},
	{"juan", L"jp"}, {"jue", L"jm"}, {"jun", L"jn"}, {"ka", L"ka"}, {"kai", L"kl"}, {"kan", L"kj"}, {"kang", L"kh"}, {"kao", L"kk"},
	{"ke", L"ke"}, {"ken", L"kf"}, {"keng", L"kg"}, {"kong", L"ks"}, {"kou", L"kb"}, {"ku", L"ku"}, {"kua", L"kd"}, {"kuai", L"kc"},
	{"kuan", L"kp"}, {"kuang", L"kt"}, {"kui", L"km"}, {"kun", L"kn"}, {"kuo", L"ko"}, {"la", L"la"}, {"lai", L"ll"}, {"lan", L"lj"},
	{"lang", L"lh"}, {"lao", L"lk"}, {"le", L"le"}, {"lei", L"lq"}, {"leng", L"lg"}, {"li", L"li"}, {"lia", L"ld"}, {"lian", L"lw"},
	{"liang", L"lt"}, {"liao", L"lz"}, {"lie", L"lx"}, {"lin", L"lc"}, {"ling", L"ly"}, {"liu", L"lr"}, {"long", L"ls"}, {"lou", L"lb"},
	{"lu", L"lu"}, {"lv", L"lv"}, {"luan", L"lp"}, {"lue", L"lm"}, {"lun", L"ln"}, {"luo", L"lo"}, {"ma", L"ma"}, {"mai", L"ml"},
	{"man", L"mj"}, {"mang", L"mh"}, {"mao", L"mk"}, {"me", L"me"}, {"mei", L"mq"}, {"men", L"mf"}, {"meng", L"mg"}, {"mi", L"mi"},
	{"mian", L"mw"}, {"miao", L"mz"}, {"mie", L"mx"}, {"min", L"mc"}, {"ming", L"my"}, {"miu", L"mr"}, {"mo", L"mo"}, {"mou", L"mb"},
	{"mu", L"mu"}, {"na", L"na"}, {"nai", L"nl"}, {"nan", L"nj"}, {"nang", L"nh"}, {"nao", L"nk"}, {"ne", L"ne"}, {"nei", L"nq"},
	{"nen", L"nf"}, {"neng", L"ng"}, {"ni", L"ni"}, {"nian", L"nw"}, {"niang", L"nt"}, {"niao", L"nz"}, {"nie", L"nx"}, {"nin", L"nc"},
	{"ning", L"ny"}, {"niu", L"nr"}, {"nong", L"ns"}, {"nu", L"nu"}, {"nv", L"nv"}, {"nuan", L"np"}, {"nue", L"nm"}, {"nuo", L"no"},
	{"o", L"oo"}, {"ou", L"ob"}, {"pa", L"pa"}, {"pai", L"pl"}, {"pan", L"pj"}, {"pang", L"ph"}, {"pao", L"pk"}, {"pei", L"pq"},
	{"pen", L"pf"}, {"peng", L"pg"}, {"pi", L"pi"}, {"pian", L"pw"}, {"piao", L"pz"}, {"pie", L"px"}, {"pin", L"pc"}, {"ping", L"py"},
	{"po", L"po"}, {"pu", L"pu"}, {"qi", L"qi"}, {"qia", L"qd"}, {"qian", L"qw"}, {"qiang", L"qt"}, {"qiao", L"qz"}, {"qie", L"qx"},
	{"qin", L"qc"}, {"qing", L"qy"}, {"qiong", L"qs"}, {"qiu", L"qr"}, {"qu", L"qu"}, {"quan", L"qp"}, {"que", L"qm"}, {"qun", L"qn"},
	{"ran", L"rj"}, {"rang", L"rh"}, {"rao", L"rk"}, {"re", L"re"}, {"ren", L"rf"}, {"reng", L"rg"}, {"ri", L"ri"}, {"rong", L"rs"},
	{"rou", L"rb"}, {"ru", L"ru"}, {"ruan", L"rp"}, {"rui", L"rm"}, {"run", L"rn"}, {"ruo", L"ro"}, {"sa", L"sa"}, {"sai", L"sl"},
	{"san", L"sj"}, {"sang", L"sh"}, {"sao", L"sk"}, {"se", L"se"}, {"sen", L"sf"}, {"seng", L"sg"}, {"sha", L"va"}, {"shai", L"vl"},
	{"shan", L"vj"}, {"shang", L"vh"}, {"shao", L"vk"}, {"she", L"ve"}, {"shen", L"vf"}, {"sheng", L"vg"}, {"shi", L"vi"}, {"shou", L"vb"},
	{"shu", L"vu"}, {"shua", L"vd"}, {"shuai", L"vc"}, {"shuan", L"vp"}, {"shuang", L"vt"}, {"shui", L"vm"}, {"shun", L"vn"},
	{"shuo", L"vo"}, {"si", L"si"}, {"song", L"ss"}, {"sou", L"sb"}, {"su", L"su"}, {"suan", L"sp"}, {"sui", L"sm"}, {"sun", L"sn"},
	{"suo", L"so"}, {"ta", L"ta"}, {"tai", L"tl"}, {"tan", L"tj"}, {"tang", L"th"}, {"tao", L"tk"}, {"te", L"te"}, {"teng", L"tg"},
	{"ti", L"ti"}, {"tian", L"tw"}, {"tiao", L"tz"}, {"tie", L"tx"}, {"ting", L"ty"}, {"tong", L"ts"}, {"tou", L"tb"}, {"tu", L"tu"},
	{"tuan", L"tp"}, {"tui", L"tm"}, {"tun", L"tn"}, {"tuo", L"to"}, {"wa", L"wa"}, {"wai", L"wl"}, {"wan", L"wj"}, {"wang", L"wh"},
	{"wei", L"wq"}, {"wen", L"wf"}, {"weng", L"wg"}, {"wo", L"wo"}, {"wu", L"wu"}, {"xi", L"xi"}, {"xia", L"xd"}, {"xian", L"xw"},
	{"xiang", L"xt"}, {"xiao", L"xz"}, {"xie", L"xx"}, {"xin", L"xc"}, {"xing", L"xy"}, {"xiong", L"xs"}, {"xiu", L"xr"}, {"xu", L"xu"},
	{"xuan", L"xp"}, {"xue", L"xm"}, {"xun", L"xn"}, {"ya", L"ya"}, {"yan", L"yj"}, {"yang", L"yh"}, {"yao", L"yk"}, {"ye", L"ye"},
	{"yi", L"yi"}, {"yin", L"yc"}, {"ying", L"yy"}, {"yo", L"yo"}, {"yong", L"ys"}, {"you", L"yb"}, {"yu", L"yu"}, {"yuan", L"yp"},
	{"yue", L"ym"}, {"yun", L"yn"}, {"za", L"za"}, {"zai", L"zl"}, {"zan", L"zj"}, {"zang", L"zh"}, {"zao", L"zk"}, {"ze", L"ze"},
	{"zei", L"zq"}, {"zen", L"zf"}, {"zeng", L"zg"}, {"zha", L"aa"}, {"zhai", L"al"}, {"zhan", L"aj"}, {"zhang", L"ah"}, {"zhao", L"ak"},
	{"zhe", L"ae"}, {"zhen", L"af"}, {"zheng", L"ag"}, {"zhi", L"ai"}, {"zhong", L"as"}, {"zhou", L"ab"}, {"zhu", L"au"}, {"zhua", L"ad"},
	{"zhuai", L"ac"}, {"zhuan", L"ap"}, {"zhuang", L"at"}, {"zhui", L"am"}, {"zhun", L"an"}, {"zhuo", L"ao"}, {"zi", L"zi"},
	{"zong", L"zs"}, {"zou", L"zb"}, {"zu", L"zu"}, {"zuan", L"zp"}, {"zui", L"zm"}, {"zun", L"zn"}, {"zuo", L"zo"}, {"ei", L"oq"},
	{"cen", L"cf"}, {"dei", L"dq"}, {"n", L"n"}, {"lve", L"lm"}, {"nve", L"nm"}, {"pou", L"pb"}, {"zhei", L"aq"}, {"dia", L"dd"},
	{"nou", L"nb"},
};

const std::unordered_map<std::string, std::wstring> SougouPyArr = {
	{"a", L"oa"}, {"ai", L"ol"}, {"an", L"oj"}, {"ang", L"oh"}, {"ao", L"ok"}, {"ba", L"ba"}, {"bai", L"bl"}, {"ban", L"bj"},
	{"bang", L"bh"}, {"bao", L"bk"}, {"bei", L"bz"}, {"ben", L"bf"}, {"beng", L"bg"}, {"bi", L"bi"}, {"bian", L"bm"}, {"biao", L"bc"},
	{"bie", L"bx"}, {"bin", L"bn"}, {"bing", L"bz"}, {"bo", L"bo"}, {"bu", L"bu"}, {"ca", L"ca"}, {"cai", L"cl"}, {"can", L"cj"},
	{"cang", L"ch"}, {"cao", L"ck"}, {"ce", L"ce"}, {"ceng", L"cg"}, {"cha", L"ia"}, {"chai", L"il"}, {"chan", L"ij"}, {"chang", L"ih"},
	{"chao", L"ik"}, {"che", L"ie"}, {"chen", L"if"}, {"cheng", L"ig"}, {"chi", L"ii"}, {"chong", L"is"}, {"chou", L"ib"}, {"chu", L"iu"},
	{"chuai", L"iy"}, {"chuan", L"ir"}, {"chuang", L"id"}, {"chui", L"iv"}, {"chun", L"ip"}, {"chuo", L"io"}, {"ci", L"ci"},
	{"cong", L"cs"}, {"cou", L"cb"}, {"cu", L"cu"}, {"cuan", L"cr"}, {"cui", L"cv"}, {"cun", L"cp"}, {"cuo", L"co"}, {"da", L"da"},
	{"dai", L"dl"}, {"dan", L"dj"}, {"dang", L"dh"}, {"dao", L"dk"}, {"de", L"de"}, {"deng", L"dg"}, {"di", L"di"}, {"dian", L"dm"},
	{"diao", L"dc"}, {"die", L"dx"}, {"ding", L"dz"}, {"diu", L"dq"}, {"dong", L"ds"}, {"dou", L"db"}, {"du", L"du"}, {"duan", L"dr"},
	{"dui", L"dv"}, {"dun", L"dp"}, {"duo", L"do"}, {"e", L"oe"}, {"en", L"of"}, {"er", L"or"}, {"fa", L"fa"}, {"fan", L"fj"},
	{"fang", L"fh"}, {"fei", L"fz"}, {"fen", L"ff"}, {"feng", L"fg"}, {"fo", L"fo"}, {"fou", L"fb"}, {"fu", L"fu"}, {"ga", L"ga"},
	{"gai", L"gl"}, {"gan", L"gj"}, {"gang", L"gh"}, {"gao", L"gk"}, {"ge", L"ge"}, {"gei", L"gz"}, {"gen", L"gf"}, {"geng", L"gg"},
	{"gong", L"gs"}, {"gou", L"gb"}, {"gu", L"gu"}, {"gua", L"gw"}, {"guai", L"gy"}, {"guan", L"gr"}, {"guang", L"gd"}, {"gui", L"gv"},
	{"gun", L"gp"}, {"guo", L"go"}, {"ha", L"ha"}, {"hai", L"hl"}, {"han", L"hj"}, {"hang", L"hh"}, {"hao", L"hk"}, {"he", L"he"},
	{"hei", L"hz"}, {"hen", L"hf"}, {"heng", L"hg"}, {"hong", L"hs"}, {"hou", L"hb"}, {"hu", L"hu"}, {"hua", L"hw"}, {"huai", L"hy"},
	{"huan", L"hr"}, {"huang", L"hd"}, {"hui", L"hv"}, {"hun", L"hp"}, {"huo", L"ho"}, {"ji", L"ji"}, {"jia", L"jw"}, {"jian", L"jm"},
	{"jiang", L"jd"}, {"jiao", L"jc"}, {"jie", L"jx"}, {"jin", L"jn"}, {"jing", L"jz"}, {"jiong", L"js"}, {"jiu", L"jq"}, {"ju", L"ju"},
	{"juan", L"jr"}, {"jue", L"jt"}, {"jun", L"jp"}, {"ka", L"ka"}, {"kai", L"kl"}, {"kan", L"kj"}, {"kang", L"kh"}, {"kao", L"kk"},
	{"ke", L"ke"}, {"ken", L"kf"}, {"keng", L"kg"}, {"kong", L"ks"}, {"kou", L"kb"}, {"ku", L"ku"}, {"kua", L"kw"}, {"kuai", L"ky"},
	{"kuan", L"kr"}, {"kuang", L"kd"}, {"kui", L"kv"}, {"kun", L"kp"}, {"kuo", L"ko"}, {"la", L"la"}, {"lai", L"ll"}, {"lan", L"lj"},
	{"lang", L"lh"}, {"lao", L"lk"}, {"le", L"le"}, {"lei", L"lz"}, {"leng", L"lg"}, {"li", L"li"}, {"lia", L"lw"}, {"lian", L"lm"},
	{"liang", L"ld"}, {"liao", L"lc"}, {"lie", L"lx"}, {"lin", L"ln"}, {"ling", L"lz"}, {"liu", L"lq"}, {"long", L"ls"}, {"lou", L"lb"},
	{"lu", L"lu"}, {"lv", L"lv"}, {"luan", L"lr"}, {"lue", L"lt"}, {"lun", L"lp"}, {"luo", L"lo"}, {"ma", L"ma"}, {"mai", L"ml"},
	{"man", L"mj"}, {"mang", L"mh"}, {"mao", L"mk"}, {"me", L"me"}, {"mei", L"mz"}, {"men", L"mf"}, {"meng", L"mg"}, {"mi", L"mi"},
	{"mian", L"mm"}, {"miao", L"mc"}, {"mie", L"mx"}, {"min", L"mn"}, {"ming", L"mz"}, {"miu", L"mq"}, {"mo", L"mo"}, {"mou", L"mb"},
	{"mu", L"mu"}, {"na", L"na"}, {"nai", L"nl"}, {"nan", L"nj"}, {"nang", L"nh"}, {"nao", L"nk"}, {"ne", L"ne"}, {"nei", L"nz"},
	{"nen", L"nf"}, {"neng", L"ng"}, {"ni", L"ni"}, {"nian", L"nm"}, {"niang", L"nd"}, {"niao", L"nc"}, {"nie", L"nx"}, {"nin", L"nn"},
	{"ning", L"nz"}, {"niu", L"nq"}, {"nong", L"ns"}, {"nu", L"nu"}, {"nv", L"nv"}, {"nuan", L"nr"}, {"nue", L"nt"}, {"nuo", L"no"},
	{"o", L"oo"}, {"ou", L"ob"}, {"pa", L"pa"}, {"pai", L"pl"}, {"pan", L"pj"}, {"pang", L"ph"}, {"pao", L"pk"}, {"pei", L"pz"},
	{"pen", L"pf"}, {"peng", L"pg"}, {"pi", L"pi"}, {"pian", L"pm"}, {"piao", L"pc"}, {"pie", L"px"}, {"pin", L"pn"}, {"ping", L"pz"},
	{"po", L"po"}, {"pu", L"pu"}, {"qi", L"qi"}, {"qia", L"qw"}, {"qian", L"qm"}, {"qiang", L"qd"}, {"qiao", L"qc"}, {"qie", L"qx"},
	{"qin", L"qn"}, {"qing", L"qz"}, {"qiong", L"qs"}, {"qiu", L"qq"}, {"qu", L"qu"}, {"quan", L"qr"}, {"que", L"qt"}, {"qun", L"qp"},
	{"ran", L"rj"}, {"rang", L"rh"}, {"rao", L"rk"}, {"re", L"re"}, {"ren", L"rf"}, {"reng", L"rg"}, {"ri", L"ri"}, {"rong", L"rs"},
	{"rou", L"rb"}, {"ru", L"ru"}, {"ruan", L"rr"}, {"rui", L"rv"}, {"run", L"rp"}, {"ruo", L"ro"}, {"sa", L"sa"}, {"sai", L"sl"},
	{"san", L"sj"}, {"sang", L"sh"}, {"sao", L"sk"}, {"se", L"se"}, {"sen", L"sf"}, {"seng", L"sg"}, {"sha", L"ua"}, {"shai", L"ul"},
	{"shan", L"uj"}, {"shang", L"uh"}, {"shao", L"uk"}, {"she", L"ue"}, {"shen", L"uf"}, {"sheng", L"ug"}, {"shi", L"ui"}, {"shou", L"ub"},
	{"shu", L"uu"}, {"shua", L"uw"}, {"shuai", L"uy"}, {"shuan", L"ur"}, {"shuang", L"ud"}, {"shui", L"uv"}, {"shun", L"up"},
	{"shuo", L"uo"}, {"si", L"si"}, {"song", L"ss"}, {"sou", L"sb"}, {"su", L"su"}, {"suan", L"sr"}, {"sui", L"sv"}, {"sun", L"sp"},
	{"suo", L"so"}, {"ta", L"ta"}, {"tai", L"tl"}, {"tan", L"tj"}, {"tang", L"th"}, {"tao", L"tk"}, {"te", L"te"}, {"teng", L"tg"},
	{"ti", L"ti"}, {"tian", L"tm"}, {"tiao", L"tc"}, {"tie", L"tx"}, {"ting", L"tz"}, {"tong", L"ts"}, {"tou", L"tb"}, {"tu", L"tu"},
	{"tuan", L"tr"}, {"tui", L"tv"}, {"tun", L"tp"}, {"tuo", L"to"}, {"wa", L"wa"}, {"wai", L"wl"}, {"wan", L"wj"}, {"wang", L"wh"},
	{"wei", L"wz"}, {"wen", L"wf"}, {"weng", L"wg"}, {"wo", L"wo"}, {"wu", L"wu"}, {"xi", L"xi"}, {"xia", L"xw"}, {"xian", L"xm"},
	{"xiang", L"xd"}, {"xiao", L"xc"}, {"xie", L"xx"}, {"xin", L"xn"}, {"xing", L"xz"}, {"xiong", L"xs"}, {"xiu", L"xq"}, {"xu", L"xu"},
	{"xuan", L"xr"}, {"xue", L"xt"}, {"xun", L"xp"}, {"ya", L"ya"}, {"yan", L"yj"}, {"yang", L"yh"}, {"yao", L"yk"}, {"ye", L"ye"},
	{"yi", L"yi"}, {"yin", L"yn"}, {"ying", L"yz"}, {"yo", L"yo"}, {"yong", L"ys"}, {"you", L"yb"}, {"yu", L"yu"}, {"yuan", L"yr"},
	{"yue", L"yt"}, {"yun", L"yp"}, {"za", L"za"}, {"zai", L"zl"}, {"zan", L"zj"}, {"zang", L"zh"}, {"zao", L"zk"}, {"ze", L"ze"},
	{"zei", L"zz"}, {"zen", L"zf"}, {"zeng", L"zg"}, {"zha", L"va"}, {"zhai", L"vl"}, {"zhan", L"vj"}, {"zhang", L"vh"}, {"zhao", L"vk"},
	{"zhe", L"ve"}, {"zhen", L"vf"}, {"zheng", L"vg"}, {"zhi", L"vi"}, {"zhong", L"vs"}, {"zhou", L"vb"}, {"zhu", L"vu"}, {"zhua", L"vw"},
	{"zhuai", L"vy"}, {"zhuan", L"vr"}, {"zhuang", L"vd"}, {"zhui", L"vv"}, {"zhun", L"vp"}, {"zhuo", L"vo"}, {"zi", L"zi"},
	{"zong", L"zs"}, {"zou", L"zb"}, {"zu", L"zu"}, {"zuan", L"zr"}, {"zui", L"zv"}, {"zun", L"zp"}, {"zuo", L"zo"}, {"ei", L"oz"},
	{"cen", L"cf"}, {"dei", L"dw"}, {"n", L"n"}, {"lve", L"lt"}, {"nve", L"nt"}, {"pou", L"pb"}, {"zhei", L"vz"}, {"dia", L"dw"},
	{"nou", L"nb"},
};

const std::unordered_map<std::string, std::wstring> ZiRanMaPyArr = {
	{"a", L"aa"}, {"ai", L"ai"}, {"an", L"an"}, {"ang", L"ah"}, {"ao", L"ao"}, {"ba", L"ba"}, {"bai", L"bl"}, {"ban", L"bj"},
	{"bang", L"bh"}, {"bao", L"bk"}, {"bei", L"bz"}, {"ben", L"bf"}, {"beng", L"bg"}, {"bi", L"bi"}, {"bian", L"bm"}, {"biao", L"bc"},
	{"bie", L"bx"}, {"bin", L"bn"}, {"bing", L"by"}, {"bo", L"bo"}, {"bu", L"bu"}, {"ca", L"ca"}, {"cai", L"cl"}, {"can", L"cj"},
	{"cang", L"ch"}, {"cao", L"ck"}, {"ce", L"ce"}, {"ceng", L"cg"}, {"cha", L"ia"}, {"chai", L"il"}, {"chan", L"ij"}, {"chang", L"ih"},
	{"chao", L"ik"}, {"che", L"ie"}, {"chen", L"if"}, {"cheng", L"ig"}, {"chi", L"ii"}, {"chong", L"is"}, {"chou", L"ib"}, {"chu", L"iu"},
	{"chuai", L"iy"}, {"chuan", L"ir"}, {"chuang", L"id"}, {"chui", L"iv"}, {"chun", L"ip"}, {"chuo", L"io"}, {"ci", L"ci"},
	{"cong", L"cs"}, {"cou", L"cb"}, {"cu", L"cu"}, {"cuan", L"cr"}, {"cui", L"cv"}, {"cun", L"cp"}, {"cuo", L"co"}, {"da", L"da"},
	{"dai", L"dl"}, {"dan", L"dj"}, {"dang", L"dh"}, {"dao", L"dk"}, {"de", L"de"}, {"deng", L"dg"}, {"di", L"di"}, {"dian", L"dm"},
	{"diao", L"dc"}, {"die", L"dx"}, {"ding", L"dy"}, {"diu", L"dq"}, {"dong", L"ds"}, {"dou", L"db"}, {"du", L"du"}, {"duan", L"dr"},
	{"dui", L"dv"}, {"dun", L"dp"}, {"duo", L"do"}, {"e", L"ee"}, {"en", L"en"}, {"er", L"er"}, {"fa", L"fa"}, {"fan", L"fj"},
	{"fang", L"fh"}, {"fei", L"fz"}, {"fen", L"ff"}, {"feng", L"fg"}, {"fo", L"fo"}, {"fou", L"fb"}, {"fu", L"fu"}, {"ga", L"ga"},
	{"gai", L"gl"}, {"gan", L"gj"}, {"gang", L"gh"}, {"gao", L"gk"}, {"ge", L"ge"}, {"gei", L"gz"}, {"gen", L"gf"}, {"geng", L"gg"},
	{"gong", L"gs"}, {"gou", L"gb"}, {"gu", L"gu"}, {"gua", L"gw"}, {"guai", L"gy"}, {"guan", L"gr"}, {"guang", L"gd"}, {"gui", L"gv"},
	{"gun", L"gp"}, {"guo", L"go"}, {"ha", L"ha"}, {"hai", L"hl"}, {"han", L"hj"}, {"hang", L"hh"}, {"hao", L"hk"}, {"he", L"he"},
	{"hei", L"hz"}, {"hen", L"hf"}, {"heng", L"hg"}, {"hong", L"hs"}, {"hou", L"hb"}, {"hu", L"hu"}, {"hua", L"hw"}, {"huai", L"hy"},
	{"huan", L"hr"}, {"huang", L"hd"}, {"hui", L"hv"}, {"hun", L"hp"}, {"huo", L"ho"}, {"ji", L"ji"}, {"jia", L"jw"}, {"jian", L"jm"},
	{"jiang", L"jd"}, {"jiao", L"jc"}, {"jie", L"jx"}, {"jin", L"jn"}, {"jing", L"jy"}, {"jiong", L"js"}, {"jiu", L"jq"}, {"ju", L"ju"},
	{"juan", L"jr"}, {"jue", L"jt"}, {"jun", L"jp"}, {"ka", L"ka"}, {"kai", L"kl"}, {"kan", L"kj"}, {"kang", L"kh"}, {"kao", L"kk"},
	{"ke", L"ke"}, {"ken", L"kf"}, {"keng", L"kg"}, {"kong", L"ks"}, {"kou", L"kb"}, {"ku", L"ku"}, {"kua", L"kw"}, {"kuai", L"ky"},
	{"kuan", L"kr"}, {"kuang", L"kd"}, {"kui", L"kv"}, {"kun", L"kp"}, {"kuo", L"ko"}, {"la", L"la"}, {"lai", L"ll"}, {"lan", L"lj"},
	{"lang", L"lh"}, {"lao", L"lk"}, {"le", L"le"}, {"lei", L"lz"}, {"leng", L"lg"}, {"li", L"li"}, {"lia", L"lw"}, {"lian", L"lm"},
	{"liang", L"ld"}, {"liao", L"lc"}, {"lie", L"lx"}, {"lin", L"ln"}, {"ling", L"ly"}, {"liu", L"lq"}, {"long", L"ls"}, {"lou", L"lb"},
	{"lu", L"lu"}, {"lv", L"lv"}, {"luan", L"lr"}, {"lue", L"lt"}, {"lun", L"lp"}, {"luo", L"lo"}, {"ma", L"ma"}, {"mai", L"ml"},
	{"man", L"mj"}, {"mang", L"mh"}, {"mao", L"mk"}, {"me", L"me"}, {"mei", L"mz"}, {"men", L"mf"}, {"meng", L"mg"}, {"mi", L"mi"},
	{"mian", L"mm"}, {"miao", L"mc"}, {"mie", L"mx"}, {"min", L"mn"}, {"ming", L"my"}, {"miu", L"mq"}, {"mo", L"mo"}, {"mou", L"mb"},
	{"mu", L"mu"}, {"na", L"na"}, {"nai", L"nl"}, {"nan", L"nj"}, {"nang", L"nh"}, {"nao", L"nk"}, {"ne", L"ne"}, {"nei", L"nz"},
	{"nen", L"nf"}, {"neng", L"ng"}, {"ni", L"ni"}, {"nian", L"nm"}, {"niang", L"nd"}, {"niao", L"nc"}, {"nie", L"nx"}, {"nin", L"nn"},
	{"ning", L"ny"}, {"niu", L"nq"}, {"nong", L"ns"}, {"nu", L"nu"}, {"nv", L"nv"}, {"nuan", L"nr"}, {"nue", L"nt"}, {"nuo", L"no"},
	{"o", L"oo"}, {"ou", L"ou"}, {"pa", L"pa"}, {"pai", L"pl"}, {"pan", L"pj"}, {"pang", L"ph"}, {"pao", L"pk"}, {"pei", L"pz"},
	{"pen", L"pf"}, {"peng", L"pg"}, {"pi", L"pi"}, {"pian", L"pm"}, {"piao", L"pc"}, {"pie", L"px"}, {"pin", L"pn"}, {"ping", L"py"},
	{"po", L"po"}, {"pu", L"pu"}, {"qi", L"qi"}, {"qia", L"qw"}, {"qian", L"qm"}, {"qiang", L"qd"}, {"qiao", L"qc"}, {"qie", L"qx"},
	{"qin", L"qn"}, {"qing", L"qy"}, {"qiong", L"qs"}, {"qiu", L"qq"}, {"qu", L"qu"}, {"quan", L"qr"}, {"que", L"qt"}, {"qun", L"qp"},
	{"ran", L"rj"}, {"rang", L"rh"}, {"rao", L"rk"}, {"re", L"re"}, {"ren", L"rf"}, {"reng", L"rg"}, {"ri", L"ri"}, {"rong", L"rs"},
	{"rou", L"rb"}, {"ru", L"ru"}, {"ruan", L"rr"}, {"rui", L"rv"}, {"run", L"rp"}, {"ruo", L"ro"}, {"sa", L"sa"}, {"sai", L"sl"},
	{"san", L"sj"}, {"sang", L"sh"}, {"sao", L"sk"}, {"se", L"se"}, {"sen", L"sf"}, {"seng", L"sg"}, {"sha", L"ua"}, {"shai", L"ul"},
	{"shan", L"uj"}, {"shang", L"uh"}, {"shao", L"uk"}, {"she", L"ue"}, {"shen", L"uf"}, {"sheng", L"ug"}, {"shi", L"ui"}, {"shou", L"ub"},
	{"shu", L"uu"}, {"shua", L"uw"}, {"shuai", L"uy"}, {"shuan", L"ur"}, {"shuang", L"ud"}, {"shui", L"uv"}, {"shun", L"up"},
	{"shuo", L"uo"}, {"si", L"si"}, {"song", L"ss"}, {"sou", L"sb"}, {"su", L"su"}, {"suan", L"sr"}, {"sui", L"sv"}, {"sun", L"sp"},
	{"suo", L"so"}, {"ta", L"ta"}, {"tai", L"tl"}, {"tan", L"tj"}, {"tang", L"th"}, {"tao", L"tk"}, {"te", L"te"}, {"teng", L"tg"},
	{"ti", L"ti"}, {"tian", L"tm"}, {"tiao", L"tc"}, {"tie", L"tx"}, {"ting", L"ty"}, {"tong", L"ts"}, {"tou", L"tb"}, {"tu", L"tu"},
	{"tuan", L"tr"}, {"tui", L"tv"}, {"tun", L"tp"}, {"tuo", L"to"}, {"wa", L"wa"}, {"wai", L"wl"}, {"wan", L"wj"}, {"wang", L"wh"},
	{"wei", L"wz"}, {"wen", L"wf"}, {"weng", L"wg"}, {"wo", L"wo"}, {"wu", L"wu"}, {"xi", L"xi"}, {"xia", L"xw"}, {"xian", L"xm"},
	{"xiang", L"xd"}, {"xiao", L"xc"}, {"xie", L"xx"}, {"xin", L"xn"}, {"xing", L"xy"}, {"xiong", L"xs"}, {"xiu", L"xq"}, {"xu", L"xu"},
	{"xuan", L"xr"}, {"xue", L"xt"}, {"xun", L"xp"}, {"ya", L"ya"}, {"yan", L"yj"}, {"yang", L"yh"}, {"yao", L"yk"}, {"ye", L"ye"},
	{"yi", L"yi"}, {"yin", L"yn"}, {"ying", L"yy"}, {"yo", L"yo"}, {"yong", L"ys"}, {"you", L"yb"}, {"yu", L"yu"}, {"yuan", L"yr"},
	{"yue", L"yt"}, {"yun", L"yp"}, {"za", L"za"}, {"zai", L"zl"}, {"zan", L"zj"}, {"zang", L"zh"}, {"zao", L"zk"}, {"ze", L"ze"},
	{"zei", L"zz"}, {"zen", L"zf"}, {"zeng", L"zg"}, {"zha", L"va"}, {"zhai", L"vl"}, {"zhan", L"vj"}, {"zhang", L"vh"}, {"zhao", L"vk"},
	{"zhe", L"ve"}, {"zhen", L"vf"}, {"zheng", L"vg"}, {"zhi", L"vi"}, {"zhong", L"vs"}, {"zhou", L"vb"}, {"zhu", L"vu"}, {"zhua", L"vw"},
	{"zhuai", L"vy"}, {"zhuan", L"vr"}, {"zhuang", L"vd"}, {"zhui", L"vv"}, {"zhun", L"vp"}, {"zhuo", L"vo"}, {"zi", L"zi"},
	{"zong", L"zs"}, {"zou", L"zb"}, {"zu", L"zu"}, {"zuan", L"zr"}, {"zui", L"zv"}, {"zun", L"zp"}, {"zuo", L"zo"}, {"ei", L"ei"},
	{"cen", L"cf"}, {"dei", L"dz"}, {"n", L"n"}, {"lve", L"lt"}, {"nve", L"nt"}, {"pou", L"pb"}, {"zhei", L"vz"}, {"dia", L"dw"},
	{"nou", L"nb"},
};

const std::unordered_map<std::string, std::wstring>* pCurrPinyin = nullptr;
