#pragma once

#include <iostream>  // For std::cout, std::wcout
#include <comdef.h>
#include <vector>
#include <string>
#include <memory>

// Import OneNote Type Library - this generates wrapper classes
// Using raw_interfaces_only to get access to raw COM interfaces
#import "libid:0EA692EE-BB50-4E3C-AEF0-356D91732725" rename_namespace("OneNoteLib") raw_interfaces_only exclude("tagPOINT")

#include "OneNoteAction.hpp"
#include "util/LogUtil.hpp"
#include "util/BitmapUtil.hpp"

// Forward declaration - the actual implementation is in OneNoteUtil.hpp
std::vector<std::shared_ptr<BaseAction>> ParseOneNoteHierarchyXML(
	const std::wstring& xml,
	const std::wstring& iconPath,
	int iconIndex,
	int maxResults = -1);

// Simple OneNote helper using #import directive
class SimpleOneNoteHelper {
private:
	OneNoteLib::IApplicationPtr m_app; // Smart pointer type generated by #import
	bool m_initialized = false;

public:
	SimpleOneNoteHelper() {
		HRESULT hr = CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);
		if (FAILED(hr) && hr != RPC_E_CHANGED_MODE) {
			Loge(L"OneNote", L"Failed to initialize COM");
			return;
		}

		try {
			// Create OneNote Application instance using smart pointer
			hr = m_app.CreateInstance(__uuidof(OneNoteLib::Application));
			if (SUCCEEDED(hr) && m_app != nullptr) {
				m_initialized = true;
				ConsolePrintln(L"OneNote", L"Successfully connected via #import");
			} else {
				ConsolePrintln(L"OneNote", L"Failed to create OneNote instance");
			}
		} catch (_com_error& e) {
			ConsolePrintln(L"OneNote", std::wstring(L"COM Error: ") + e.ErrorMessage());
		}
	}

	~SimpleOneNoteHelper() {
		if (m_app) {
			m_app.Release();
		}
	}

	bool IsInitialized() const {
		return m_initialized;
	}

	std::wstring GetHierarchy() {
		if (!m_app) {
			return L"";
		}

		try {
			BSTR bstrXml = nullptr;

			// Call GetHierarchy with parameters
			// Signature: GetHierarchy(BSTR nodeId, HierarchyScope scope, BSTR* xml, XMLSchema schema)
			HRESULT hr = m_app->GetHierarchy(
				_bstr_t(L""), // Empty string for all notebooks
				OneNoteLib::hsPages, // Get all pages
				&bstrXml, // Output XML
				OneNoteLib::xs2013 // Schema version
			);

			if (SUCCEEDED(hr) && bstrXml) {
				std::wstring result(bstrXml);
				SysFreeString(bstrXml);
				ConsolePrintln(L"OneNote", L"Successfully retrieved hierarchy, XML length: " +
								std::to_wstring(result.length()));

				// Debug: Show XML
				// std::wstring preview = result;
				// ConsolePrintln(L"OneNote", L"XML Preview: " + preview);

				return result;
			} else {
				wchar_t buf[32];
				swprintf_s(buf, L"0x%08X", static_cast<unsigned int>(hr));
				ConsolePrintln(L"OneNote", std::wstring(L"GetHierarchy failed: ") + buf);
			}
		} catch (_com_error& e) {
			ConsolePrintln(L"OneNote", std::wstring(L"COM Error in GetHierarchy: ") + e.ErrorMessage());
		}

		return L"";
	}

	std::wstring GetPageContent(const std::wstring& pageId) {
		if (!m_app) {
			return L"";
		}

		try {
			BSTR bstrPageXml = nullptr;

			// Call GetPageContent with parameters
			// Signature: GetPageContent(BSTR pageId, BSTR* pageXml, PageInfo pageInfo, XMLSchema schema)
			HRESULT hr = m_app->GetPageContent(
				_bstr_t(pageId.c_str()), // Page ID
				&bstrPageXml, // Output XML
				OneNoteLib::piBasic, // Basic page info (no binary content)
				OneNoteLib::xs2013 // Schema version
			);

			if (SUCCEEDED(hr) && bstrPageXml) {
				std::wstring result(bstrPageXml);
				SysFreeString(bstrPageXml);
				return result;
			} else {
				wchar_t buf[32];
				swprintf_s(buf, L"0x%08X", static_cast<unsigned int>(hr));
				Loge(L"OneNote", std::wstring(L"GetPageContent failed with HRESULT: ") + buf);
			}
		} catch (_com_error& e) {
			Loge(L"OneNote", L"COM Error in GetPageContent: ", wide_to_utf8(e.ErrorMessage()).c_str());
		}

		return L"";
	}

	bool NavigateToPage(const std::wstring& pageId) {
		if (!m_app) {
			return false;
		}

		try {
			// NavigateTo(bstrHierarchyObjectID, bstrObjectID, fNewWindow)
			// Pass pageId as hierarchyObjectID, empty string for objectID, false for new window
			HRESULT hr = m_app->NavigateTo(
				_bstr_t(pageId.c_str()), // Page ID
				_bstr_t(L""), // Object ID (empty)
				VARIANT_FALSE // Don't open in new window
			);
			return SUCCEEDED(hr);
		} catch (_com_error& e) {
			ConsolePrintln(L"OneNote", std::wstring(L"COM Error in NavigateTo: ") + e.ErrorMessage());
			return false;
		}
	}
};
